[pytest]
addopts =  -v -s \
    --html=report.html \
    --self-contained-html \
    --alluredir=./allure-results \
    --reruns 2 \
    --reruns-delay 1 \
    -n auto  // 并行执行
testpaths = ./tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: 冒烟测试
    regression: 回归测试
addopts = -v -s \
    --html=report.html \
    --self-contained-html \
    --alluredir=./allure-results \
    --reruns 2 \
    --reruns-delay 1 \
    -n auto  // 并行执行